[package]
name = "nmap-db"
version = "0.0.1"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pcre  = "0.2"
# PCRE2_SYS_STATIC=1
pcre2 = "0.1"

[dev-dependencies]
env_logger = "0.6.0"
chrono = "0.4"
ansi_term = "0.11"
